### ISSUE TITLE
can not work in ubuntu 16.04

### ISSUE THREAD

**Issue by unicornx** [tinyclub/cloud-lab#1]
followup http://tinylab.org/how-to-deploy-cloud-labs/ procedure

work with ubuntu 14.04 LTS, but failed with 16.04 LTS

doubt the `tools/docker/pull` script can't work, due to it crashed when I executed the commands till the second line `. $TOP_DIR/tools/docker/config $* >/dev/null`, after I input `yes` when the prompt appeared and query `yes/no`.

**Comment by lzufalcon** [comment]
@unicornx 问题解决没？解决了就先关了。

**Comment by unicornx** [comment]
你先关了吧，后来一直没空试呢
