### ISSUE TITLE
linux-lab-0.11中 "minix.ko" version magic 错误

### ISSUE THREAD

**Issue by popipo-yr** [tinyclub/cloud-lab#2]
minix: version magic '4.9.49-moby SMP mod_unload ' should be 'xxxxx mod_unload '

**Comment by lzufalcon** [comment]
@popipo-yr 你好，最近比较忙，没注意这块，这个错误是什么情况下出现的呢？

**Comment by lzufalcon** [comment]
@popipo-yr 你好，这个问题已经解决了，minix模块版本没有来得及更新，在这里有解释。 https://github.com/tinyclub/linux-0.11-lab/issues/14
