### ISSUE TITLE
Permission issue of the linux-lab under cloud-lab.

### ISSUE THREAD

**Issue by bettmann** [tinyclub/cloud-lab#3]
I think here should be change to 'root' user Or add user 'ubuntu' to 'sudo' group, right?
------
ubuntu@linux-lab:/labs/linux-lab$ make boot

Downloading board bsp ...
git submodule update  --init --remote /labs/linux-lab/boards/mipsel/malta/bsp
fatal: could not create work tree dir 'boards/mipsel/malta/bsp'.: Permission denied
Clone of 'https://gitee.com/tinylab/qemu-mipsel-malta.git' into submodule path 'boards/mipsel/malta/bsp' failed
make: *** [bsp-source] Error 1
ubuntu@linux-lab:/labs/linux-lab$ whoami 
ubuntu
ubuntu@linux-lab:/labs/linux-lab$

**Comment by lzufalcon** [comment]
@bettmann hi, it depends on who cloned cloud-lab, if root, please change it to normal user, otherwise, sudo is required.

```
$ sudo chown $USER:$USER -R linux-lab/
```

**Comment by lzufalcon** [comment]
@bettmann close this for no response from reporter.
